"""empty message

Revision ID: e5a4cbdd0ff3
Revises: d83f4ce8fdd7
Create Date: 2021-11-04 02:28:28.570301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a4cbdd0ff3'
down_revision = 'd83f4ce8fdd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_profile', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_profile', sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
